// <auto-generated />
using System;
using Engenhos.AzureDevOps.Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Engenhos.AzureDevOps.Infraestrutura.Migrations
{
    [DbContext(typeof(EngenhosAzureDevOpsContexto))]
    partial class EngenhosAzureDevOpsContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Engenhos.AzureDevOps.Dominio.WorkItems.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime>("DataCriacaoWorkItem");

                    b.Property<int>("IdWorkItem");

                    b.Property<string>("Tipo")
                        .IsRequired();

                    b.Property<string>("Titulo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("IdWorkItem")
                        .IsUnique();

                    b.ToTable("WorkItem");
                });
#pragma warning restore 612, 618
        }
    }
}
